Completed CSS Brochure Form
JoshuaAaronBaker/c0622-code-solutions pull request #16
Opened 2022-06-30 16:57 UTC by JoshuaAaronBaker

<img width="502" alt="Screen Shot 2022-06-30 at 9 56 46 AM" src="https://user-images.githubusercontent.com/91937935/176734892-0f184eec-3ae8-47fb-8d61-a3c41206ff1b.png">

2022-06-30 17:22 UTC, codingcodymiller requested changes
Hey Josh, your form is too narrow as compared to the example, please revise and submit a new screenshot with your revision.

2022-06-30 18:52 UTC, codingcodymiller requested changes

2022-06-30 18:52 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  opacity: 0.7;
You shouldn't use opacity to change the color of text, use the `color` property

2022-06-30 20:03 UTC, JoshuaAaronBaker commented
<img width="566" alt="Screen Shot 2022-06-30 at 12 52 28 PM" src="https://user-images.githubusercontent.com/91937935/176767805-d7686c87-02e7-47ed-8efc-738342df9622.png">

2022-07-01 17:34 UTC, codingcodymiller requested changes

2022-07-01 18:18 UTC, codingcodymiller approved these changes
Nice work!

2022-07-01 20:06 UTC, merged