Completed CSS Canvas Medical - Joshua Baker
JoshuaAaronBaker/c0622-code-solutions pull request #30
Opened 2022-07-07 08:21 UTC by JoshuaAaronBaker

<img width="1425" alt="Screen Shot 2022-07-07 at 1 20 03 AM" src="https://user-images.githubusercontent.com/91937935/177726816-cd3b99ca-7566-4fcc-86d2-a4b76aabd665.png">
<img width="1424" alt="Screen Shot 2022-07-07 at 1 20 28 AM" src="https://user-images.githubusercontent.com/91937935/177726845-95bc7fde-d495-404e-9af3-b8531fc8ddbb.png">
<img width="1426" alt="Screen Shot 2022-07-07 at 1 20 38 AM" src="https://user-images.githubusercontent.com/91937935/177726846-689d3937-115e-4947-92ab-3585918a0ed9.png">

2022-07-07 17:08 UTC, codingcodymiller requested changes
Hey Josh! A few things:
1. You are missing the overlay over the hero image, it is too bright as compared to the example.
2. The text color of the "Ready to learn more?" headline does not match the example
3. The links in the final row are misaligned with the rest of the content

Please revise and submit a new screenshot with your revision.

2022-07-11 07:00 UTC, JoshuaAaronBaker commented
<img width="979" alt="Screen Shot 2022-07-10 at 11 56 22 PM" src="https://user-images.githubusercontent.com/91937935/178206561-b89b4d31-6e16-43d9-a456-b6f7c49007fa.png">
<img width="922" alt="Screen Shot 2022-07-10 at 11 56 33 PM" src="https://user-images.githubusercontent.com/91937935/178206573-b3b8f760-518c-48df-8a0c-71cc118aecc6.png">
<img width="1199" alt="Screen Shot 2022-07-10 at 11 56 42 PM" src="https://user-images.githubusercontent.com/91937935/178206574-4bb34b8b-a3c1-43a4-9b5a-6f29f2daa23c.png">


I dont understand why the Ready to learn more text is a different font color.
<img width="457" alt="Screen Shot 2022-07-10 at 11 59 55 PM" src="https://user-images.githubusercontent.com/91937935/178206809-530c0169-4a6b-4dee-82c2-61821e12a7e2.png">

2022-07-11 17:27 UTC, codingcodymiller requested changes
Have you tried inspecting the element to see what styling is currently being applied to it? It may be a specificity issue.

2022-07-18 05:06 UTC, JoshuaAaronBaker commented
![Uploading Screen Shot 2022-07-17 at 10.05.06 PM.png…]()

2022-07-18 16:16 UTC, codingcodymiller requested changes

2022-07-18 16:16 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
You shouldn't make numbered classes like this. You could make this a utility class named something like `large-container` that only has the `max-width` property declaration, and apply it in addition to the actual `container` class

2022-07-18 16:16 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.margin3 {
What does the `3` represent?

2022-07-18 16:16 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.padding1 {
`1`?

2022-07-18 16:16 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.padding {
How much padding?

2022-07-18 16:16 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.sec-3-font {
What is `sec-3`?

2022-07-18 16:16 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +.p2-font {
`p2`?

2022-07-26 16:01 UTC, codingcodymiller approved these changes

2022-07-27 17:36 UTC, merged